# 
# echo AQDCm15bxVgKHRAA8uwD5E7VO2AKRVfK7IwHyA== | base64
# QVFEQ20xNWJ4VmdLSFJBQTh1d0Q1RTdWTzJBS1JWZks3SXdIeUE9PQo=
# ceph secret
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: kube-system
data:
  key: QVFEQ20xNWJ4VmdLSFJBQTh1d0Q1RTdWTzJBS1JWZks3SXdIeUE9PQo=

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-system-pv
  namespace: kube-system
  labels:
    app: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "kube-system-pv"
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  cephfs:
    monitors:
    - "192.168.60.41:6789"
    - "192.168.60.42:6789"
    - "192.168.60.43:6789"
    path: /k8s-deploy/kube-system
    user: admin
    secretRef:
      name: ceph-secret

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-system-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: kube-system-pv
  selector:
    matchLabels:
      app: kube-system

