---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
      - name: timezone
        hostPath:
          path: /etc/timezone
          type: File
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      - name: elasticsearch-data
        hostPath:
          path: /local-storage/kube-system/elasticsearch
      imagePullSecrets:
      - name: devops-reg.io
      nodeSelector:
        store: localstorage
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - elasticsearch
            topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch
        image: devops-reg.io/public/elasticsearch-oss:6.2.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: timezone
          mountPath: "/etc/timezone"
        - name: localtime
          mountPath: "/etc/localtime"
        - name: elasticsearch-data
          mountPath: "/usr/share/elasticsearch/data"
        securityContext:
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms16g -Xmx16g"
        command: #[ tail, -f, /etc/hosts]
        - "elasticsearch"
        - "-Epath.data=/usr/share/elasticsearch/data"
        - "-Epath.logs=/usr/share/elasticsearch/data"
        - "-Ecluster.name=es-cluster"
        - "-Ebootstrap.memory_lock=false"
        - "-Enetwork.host=0.0.0.0"
        - "-Ediscovery.zen.minimum_master_nodes=2"
        - "-Ediscovery.zen.ping.unicast.hosts=elasticsearch-0.elasticsearch-headless"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: 
          requests:
            memory: "8Gi"
          limits:
            memory: "32Gi"
