---
apiVersion: v1
kind: Service
metadata:
  name: nginx-kibana
  namespace: kube-system
  labels:
    app: nginx-kibana
spec:
  type: NodePort
  selector:
    app: nginx-kibana
  ports:
  - name: port-8001
    port: 8001
    nodePort: 30007
