---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
  namespace: kube-system
  labels:
    app: kibana
spec:
  serviceName: kibana-headless
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      volumes:
      - name: timezone
        hostPath:
          path: /etc/timezone
          type: File
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      imagePullSecrets:
      - name: devops-reg.io
      nodeSelector:
        role: worker
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - kibana
      #       topologyKey: kubernetes.io/hostname
      containers:
      - name: kibana
        image: devops-reg.io/public/kibana-oss:6.2.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: timezone
          mountPath: "/etc/timezone"
        - name: localtime
          mountPath: "/etc/localtime"
        env:
        - name: SERVER_NAME
          value: kibana  
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-headless:9200
        # - name: SERVER_BASEPATH
        #   value: /api/v1/namespaces/kube-system/services/kibana/proxy
        # - name: XPACK_MONITORING_ENABLED
        #   value: "false"
        # - name: XPACK_SECURITY_ENABLED
        #   value: "false"
        # command: ["tail", "-f", "/etc/hosts"]  
        ports:
        - containerPort: 5601
        resources: 
          requests:
            memory: "4Gi"
          limits:
            memory: "16Gi"
