---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: kube-system
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - name: port-9200
    port: 9200
  - name: port-9300
    port: 9300
