---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-kibana
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-kibana
    spec:
      volumes:
      - name: timezone
        hostPath:
          path: /etc/timezone
          type: File
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: File
      - name: kube-system-pvc
        persistentVolumeClaim:
          claimName: kube-system-pvc
      imagePullSecrets:
      - name: devops-reg.io
      nodeSelector:
        role: worker
      containers:
      - name: nginx-kibana
        image: devops-reg.io/public/nginx:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: timezone
          mountPath: "/etc/timezone"
        - name: localtime
          mountPath: "/etc/localtime"
        - name: kube-system-pvc
          mountPath: /etc/nginx/conf.d
          subPath: nginx-kibana
        # command: ["tail", "-f", "/etc/hosts"]  
        ports:
        - containerPort: 8001
        resources: 
          requests:
            memory: "1Gi"
          limits:
            memory: "4Gi"